name: Agent Task

title: "[AGENT] "
labels: ["agent-task"]
body:
  - type: markdown
    attributes:
      value: |


  - type: textarea
    id: context
    attributes:

    validations:
      required: true

  - type: textarea
    id: scope
    attributes:

    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:

    validations:
      required: true

  - type: textarea
    id: risks
    attributes:


  - type: textarea
    id: notes
    attributes:
=======
      label: Additional Notes
      description: |
        Дополнительная информация, ссылки, ADR, обсуждения.
      placeholder: |
        - См. ARCHITECTURE.md для понимания структуры
        - Проверьте automation_policy.yaml для правил
        - Связанные issue: #123, #456

  - type: checkboxes
    id: checklist
    attributes:
      label: Agent Checklist
      description: Проверки для агента перед закрытием задачи
      options:
        - label: Код соответствует стандартам (ruff + black + mypy)
          required: false
        - label: Тесты добавлены/обновлены
          required: false
        - label: Покрытие >= 85%
          required: false
        - label: CI проходит успешно
          required: false
        - label: Документация обновлена
          required: false
        - label: Pre-commit hooks проходят
          required: false

