name: Agent Task

labels: ["agent-task"]
body:
  - type: markdown
    attributes:
      value: |


  - type: textarea
    id: context
    attributes:
      label: Контекст / Обоснование

    validations:
      required: true

  - type: textarea
    id: scope
    attributes:

    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:

  - type: dropdown
    id: priority
    attributes:
      label: Приоритет

      default: 1
    validations:
      required: true

  - type: dropdown

      placeholder: |
        Зависит от:
        - #123 должен быть закрыт первым
        - ADR-0003 должен быть утверждён
        
        Блокирует:
        - #456
    validations:
      required: false

  - type: input
    id: estimated_time
    attributes:
      label: Оценка времени
      description: Примерное время выполнения (опционально)
      placeholder: "2h, 1d, 3d"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Дополнительные заметки
      description: |
        Любая дополнительная информация:
        - Ссылки на примеры кода
        - Ссылки на внешние ресурсы
        - Особые инструкции для агента
      placeholder: |
        Полезные ссылки:
        - Похожая реализация: https://github.com/example/repo
        - Документация API: https://docs.example.com
        
        Особые требования:
        - Использовать asyncio для операций I/O
        - Следовать паттерну из existing_module.py
    validations:
      required: false

  - type: checkboxes
    id: agent_checklist
    attributes:
      label: Pre-flight checklist
      description: Убедитесь, что задача готова для агента
      options:
        - label: Задача чётко сформулирована и атомарна
          required: true
        - label: Критерии приёмки измеримы
          required: true
        - label: Область изменений определена (scope)
          required: true
        - label: Прочитаны `.github/COPILOT_INSTRUCTIONS.md` и `automation_policy.yaml`
          required: false
        - label: Связанная документация обновлена (если нужно)
          required: false
=======
    id: complexity
    attributes:
      label: Оценка сложности
      description: Примерная оценка объёма работы
      options:
        - XS (< 1 час, < 50 строк)
        - S (1-2 часа, 50-200 строк)
        - M (2-4 часа, 200-500 строк)
        - L (4-8 часов, 500-1000 строк)
        - XL (> 8 часов, требует разбиения)
      default: 2
    validations:
      required: true

  - type: checkboxes
    id: requires_review
    attributes:
      label: Требует Human Review?
      description: |
        Отметьте, если изменения требуют обязательного ревью человеком
        (см. automation_policy.yaml для критериев)
      options:
        - label: Public API change
        - label: Major version bump
        - label: ADR modification
        - label: Security policy change
        - label: Breaking change

  - type: textarea
    id: notes
    attributes:
      label: Дополнительные заметки
      description: |
        Любая дополнительная информация: ссылки, обсуждения, ADR, примеры.
      placeholder: |
        - Ссылка на PR с похожей задачей: #123
        - ADR: DECISIONS/0005-cache-strategy.md
        - Пример использования: https://example.com/docs/metrics

  - type: markdown
    attributes:
      value: |
        ---
        
        **Для агента:** После создания issue прочитайте `.github/COPILOT_INSTRUCTIONS.md` 
        для полного контекста и следуйте автономному циклу разработки.
        
        **Для человека:** Этот шаблон структурирует задачи так, чтобы агент мог работать 
        максимально автономно при соблюдении всех качественных стандартов.
=======
description: Structured task for Copilot agent
labels: ["agent-task"]
title: "agent: <кратко>"
body:
  - type: textarea
    id: context
    attributes:
      label: Context / Rationale
      description: Почему это нужно? Ссылки на исходные обсуждения / проблемы.
      placeholder: >-
        Кратко зачем. Ссылка на issue/ADR/roadmap пункт.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope (In / Out)
      description: Что включено и что явно исключено.
      placeholder: >-
        In: ...\nOut: ...
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Проверяемые условия завершения (тесты, файлы, показатели).
      placeholder: >-
        - Тесты добавлены\n- Покрытие не ниже ...\n- Нет новых mypy ошибок
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks / Edge Cases
      description: Какие риски и как их минимизировать.
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: ADR, ссылки, наброски.
>>>>>>> Stashed changes
>>>>>>> copilot/fix-ceecdf58-182b-4ca5-918c-d8a68775e055
