name: Agent Task
description: Structured task for Copilot agent
title: "[AGENT] "
labels: ["agent-task"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Agent Task Template
        
        Используйте этот шаблон для создания структурированных задач для Copilot агента.
        Чётко определите контекст, область действия и критерии приёмки.

  - type: textarea
    id: context
    attributes:
      label: Context / Rationale
      description: |
        Почему это нужно? Какую проблему решаем?
        Укажите ссылки на связанные issue, roadmap или обсуждения.
      placeholder: |
        Например:
        - Требуется добавить функцию умножения для расширения математических операций
        - Связано с roadmap item #123
        - Пользователи просят эту функциональность
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: |
        Что ВКЛЮЧЕНО в эту задачу и что ЯВНО ИСКЛЮЧЕНО.
        Определите границы работы.
      placeholder: |
        **Включено:**
        - Добавить функцию multiply() в example.py
        - Добавить тесты для multiply()
        - Обновить __all__ экспорт
        
        **Исключено:**
        - Деление и другие операции
        - Изменение существующих функций add/sum_all
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: |
        Измеримый набор условий для завершения задачи.
        Как проверить, что задача выполнена?
      placeholder: |
        - [ ] Функция multiply(a, b) реализована и типизирована
        - [ ] Тесты test_multiply() добавлены и проходят
        - [ ] Покрытие кода >= 85%
        - [ ] Все проверки CI зелёные
        - [ ] Документация (docstring) добавлена
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / Edge Cases
      description: |
        Возможные проблемы и как их минимизировать.
        Какие граничные случаи нужно учесть?
      placeholder: |
        - Переполнение для очень больших чисел (Python int безграничен, но стоит упомянуть)
        - Поведение с отрицательными числами (должно работать стандартно)
        - Совместимость с существующим API

  - type: textarea
    id: implementation_hints
    attributes:
      label: Implementation Hints
      description: |
        Подсказки по реализации (опционально).
        Предпочтительный подход или технические детали.
      placeholder: |
        - Следуйте стилю существующих функций (add, sum_all)
        - Используйте type hints: def multiply(a: int, b: int) -> int
        - Добавьте docstring в Google style

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: |
        Дополнительная информация, ссылки, ADR, обсуждения.
      placeholder: |
        - См. ARCHITECTURE.md для понимания структуры
        - Проверьте automation_policy.yaml для правил
        - Связанные issue: #123, #456

  - type: checkboxes
    id: checklist
    attributes:
      label: Agent Checklist
      description: Проверки для агента перед закрытием задачи
      options:
        - label: Код соответствует стандартам (ruff + black + mypy)
          required: false
        - label: Тесты добавлены/обновлены
          required: false
        - label: Покрытие >= 85%
          required: false
        - label: CI проходит успешно
          required: false
        - label: Документация обновлена
          required: false
        - label: Pre-commit hooks проходят
          required: false
