name: Agent Task
description: Шаблон задачи для автономного агента
labels:
  - agent-task
body:
  - type: markdown
    attributes:
      value: |
        Заполните поля для постановки задачи агенту. Указывайте чёткие критерии приемки.

  - type: textarea
    id: context
    attributes:
      label: Контекст
      description: Предпосылки, ссылки, связанные issue / ADR
      placeholder: Кратко опишите зачем и что требует изменения
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Что входит и что явно исключено
      placeholder: |
        Включено: ...
        Исключено: ...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Условия успешного завершения задачи
      placeholder: |
        - [ ] Поведение X
        - [ ] Тесты покрывают крайние случаи
        - [ ] Документация обновлена
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Оценка сложности
      options:
        - XS (<1h / <50 LOC)
        - S (1-2h / 50-200 LOC)
        - M (2-4h / 200-500 LOC)
        - L (4-8h / 500-1000 LOC)
        - XL (>8h / требует разбиения)
      default: 2
    validations:
      required: true

  - type: checkboxes
    id: requires_review
    attributes:
      label: Требует Human Review?
      description: |
        Отметьте, если изменения требуют обязательного ревью человеком (см. automation_policy.yaml)
      options:
        - label: Public API change
        - label: Major version bump
        - label: ADR modification
        - label: Security policy change
        - label: Breaking change

  - type: textarea
    id: notes
    attributes:
      label: Дополнительные заметки
      description: ADR, ссылки, обсуждения
      placeholder: |
        - См. ARCHITECTURE.md
        - См. automation_policy.yaml
        - Связанные issue: #123

  - type: checkboxes
    id: checklist
    attributes:
      label: Agent Checklist
      description: Проверки перед закрытием задачи
      options:
        - label: Код соответствует стандартам (ruff + black + mypy)
        - label: Тесты добавлены/обновлены
        - label: Покрытие >= 85%
        - label: CI проходит успешно
        - label: Документация обновлена
        - label: Pre-commit hooks проходят
