name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build:
        name: Build & Test (Python ${{ matrix.python-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        container: python:${{ matrix.python-version }}
        steps:
            - name: Fetch source
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git init .
                  git config --local gc.auto 0
                  git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  git -c protocol.version=2 fetch --depth=1 origin ${GITHUB_SHA}
                  git checkout FETCH_HEAD
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Pre-commit (lint/type subset)
              run: pre-commit run --all-files --show-diff-on-failure || exit 1
            - name: Lint & Type Check (explicit)
              run: |
                  ruff check .
                  ruff format --check .
                  mypy src/autonomous_dev
            - name: Tests & Coverage
              run: pytest --cov=src/autonomous_dev --cov-report=term-missing --cov-report=xml
            - name: Coverage summary
              run: |
                  python - <<'PY'
                  import xml.etree.ElementTree as ET
                  r = ET.parse('coverage.xml').getroot().attrib
                  print('LINE RATE:', r.get('line-rate'))
                  PY
    security:
        name: Security & Dependencies
        runs-on: ubuntu-latest
        needs: build
        container: python:3.11
        steps:
            - name: Fetch source
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git init .
                  git config --local gc.auto 0
                  git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  git -c protocol.version=2 fetch --depth=1 origin ${GITHUB_SHA}
                  git checkout FETCH_HEAD
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Bandit
              run: bandit -q -r src/autonomous_dev
            - name: pip-audit
              run: pip-audit --fail-on HIGH || true
            - name: Deptry
              run: deptry . --ignore-unused-dependencies
