name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build:
        name: Build & Test (Python ${{ matrix.python-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: pip
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Pre-commit (selected hooks)
              run: |
                  pip install pre-commit
                  pre-commit run --all-files --show-diff-on-failure
            - name: Lint & Type Check
              run: |
                  ruff check .
                  ruff format --check .
                  mypy src/autonomous_dev
            - name: Tests (coverage gate)
              run: pytest --cov=src/autonomous_dev --cov-report=xml
            - name: Upload coverage to Codecov
              if: ${{ success() && matrix.python-version == '3.11' }}
              uses: codecov/codecov-action@v4
              with:
                  files: coverage.xml
                  verbose: true
                  fail_ci_if_error: false
                  # Token is optional for public repos, but recommended for reliability
                  token: ${{ secrets.CODECOV_TOKEN }}

    security:
        name: Security & Dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: pip
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Pre-commit (selected hooks)
              run: |
                  pip install pre-commit
                  pre-commit run --all-files --show-diff-on-failure
            - name: Bandit
              run: bandit -q -r src/autonomous_dev
            - name: pip-audit
              run: pip-audit || true
            - name: Deptry
              run: deptry . --ignore DEP002,DEP003
