name: CI Full

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build:
        name: Build & Test (Python ${{ matrix.python-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        # Using secret directly in Codecov step; removed intermediate env variable.
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: pip
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Lint & Type Check
              run: |
                  ruff check .
                  ruff format --check .
                  mypy src/autonomous_dev
            - name: Run Tests & Generate Coverage
              run: |
                  pytest --cov=src/autonomous_dev --cov-report=xml
            - name: Upload coverage to Codecov
              if: ${{ success() && matrix.python-version == '3.11' }}
              uses: codecov/codecov-action@v4
              with:
                  # token removed: tokenless upload works for public repositories
                  files: coverage.xml
                  verbose: true
    security:
        name: Security & Dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: pip
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Bandit
              run: bandit -q -r src/autonomous_dev
            - name: pip-audit
              run: pip-audit --fail-on HIGH || true
            - name: Deptry
              run: deptry . --ignore-unused-dependencies
