name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build:
        name: Build & Test (Python ${{ matrix.python-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: pip
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Pre-commit (selected hooks)
              run: |
                  pip install pre-commit
                  pre-commit run --all-files --show-diff-on-failure
            - name: Lint & Type Check
              run: |
                  ruff check .
                  ruff format --check .
                  mypy src/autonomous_dev
            - name: Tests (coverage gate)
              run: pytest --cov=src/autonomous_dev --cov-report=xml
            - name: Upload coverage to Codecov
              if: ${{ success() && matrix.python-version == '3.11' }}
              uses: codecov/codecov-action@v4
              with:
                  files: coverage.xml
                  verbose: true
                  fail_ci_if_error: false
                  token: ${{ secrets.CODECOV_TOKEN }}

    lint:
        name: Super-Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Super-Linter
              uses: super-linter/super-linter@v8.2.0
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_ALL_CODEBASE: false
                  VALIDATE_PYTHON_BLACK: false
                  VALIDATE_PYTHON_FLAKE8: false
                  VALIDATE_PYTHON_PYLINT: false
                  VALIDATE_PYTHON_ISORT: false
                  VALIDATE_PYTHON_MYPY: false
                  VALIDATE_PYTHON_RUFF: true

    security:
        name: Security & Dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0  # Fetch all history for gitleaks
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: pip
            - name: Gitleaks - Secret Scanning
              uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Pre-commit (selected hooks)
              run: |
                  pip install pre-commit
                  pre-commit run --all-files --show-diff-on-failure
            - name: Bandit
              run: bandit -q -r src/autonomous_dev
            - name: pip-audit
              run: pip-audit || true
            - name: Deptry

