name: Nightly Extended Checks

on:
    schedule:
        - cron: "0 2 * * *"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    extended-security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
                  pip install pip-audit bandit deptry
            - name: Full pip-audit (fail on medium)
              run: pip-audit --fail-on MEDIUM
            - name: Bandit full scan
              run: bandit -r src/autonomous_dev -lll
            - name: Deptry strict
              run: deptry .

    coverage-diff:
        runs-on: ubuntu-latest
        needs: extended-security
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install .[dev]
            - name: Run tests with coverage
              run: pytest --cov=src/autonomous_dev --cov-report=xml
            - name: Save coverage artifact
              uses: actions/upload-artifact@v4
              with:
                  name: nightly-coverage
                  path: coverage.xml
