name: Release

on:
    workflow_dispatch: {}
    push:
        branches: [main]
        paths:
            - pyproject.toml

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build
              run: python -m build
            - name: Upload dist artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-packages
                  path: dist/*
            - name: Publish to PyPI
              if: startsWith(github.ref, 'refs/heads/main')
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  verbose: true
                  print-hash: true
