name: Version Consistency

on:
    pull_request:
        branches: [main]

jobs:
    version-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install minimal deps
              run: |
                  python -m pip install --upgrade pip
                  pip install tomli
            - name: Run semantic version check
              run: python scripts/check_version.py
